version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cvdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/cvdb
    command: sh -c "npx prisma db push && npm run start"
  ai-validator:
    build:
      context: ./ai-validator
    ports:
      - "3001:3001"

volumes:
  db-data:
